name: Scorecard
on:
  schedule: [{ cron: "0 9 * * 3" }]
  push: { branches: [main] }
permissions: { security-events: write, actions: read, contents: read }
jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: ossf/scorecard-action@v2.4.3
        with: { results_file: results.sarif, publish_results: true }
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: results.sarif }
